# ???????????
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/mydatabase?serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    min-idle: 1
    max-active: 5
    test-on-borrow: true
    validation-query: SELECT 1

mybatis:
  mapper-locations: mybatis/mapper/*.xml